[package]
name = "l5p-kb-rgb"
version = "0.1.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = "0.11.1"
fltk = "1.1.12"
rand = "0.8.4"

[dependencies.hidapi]
version = "1.2.6"
default-features = false
features=["linux-static-hidraw"]