[package]
name = "l5p-kb-rgb"
version = "0.5.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = "0.11.1"
fltk = "1.1.12"
rand = "0.8.4"
# https://github.com/rustdesk/rustdesk/tree/master/libs/scrap
scrap = {path = "libs/scrap"}
image = "0.23.14"

[dependencies.hidapi]
version = "1.2.6"
default-features = false
features=["linux-static-hidraw"]
