[package]
name = "legion-kb-rgb"
version = "0.8.0"
author = "4JX"
edition = "2018"
homepage = "https://github.com/4JX/L5P-Keyboard-RGB"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = "0.11.2"
fltk = "1.2.12"
rand = "0.8.4"
# https://github.com/rustdesk/rustdesk/tree/master/libs/scrap
scrap = {path = "libs/scrap"}
image = "0.23.14"
tray-item = {version = "0.5.0-alpha", git = "https://github.com/njust/tray-item-rs"}

[dependencies.hidapi]
version = "1.2.6"
default-features = false
features=["linux-static-libusb"]

[build-dependencies]
winres = "0.1.12"