[package]
name = "legion-kb-rgb"
version = "0.11.0"
authors = ["4JX"]
edition = "2018"
homepage = "https://github.com/4JX/L5P-Keyboard-RGB"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "1.2.12"
rand = "0.8.4"
# https://github.com/rustdesk/rustdesk/tree/master/libs/scrap
scrap = {path = "libs/scrap"}
image = "0.23.14"
tray-item = {version = "0.5.0-alpha", git = "https://github.com/njust/tray-item-rs"}
clap = "2.33.3"
strum ="0.23.0"
strum_macros = "0.23.1"
serde = {version = "1.0.130", features = ["derive"]}
serde_json = "1.0.70"

[dependencies.hidapi]
version = "1.2.6"
default-features = false
features=["linux-static-libusb"]

[build-dependencies]
winres = "0.1.12"

[package.metadata.vcpkg]
git = "https://github.com/microsoft/vcpkg"
rev = "356918c"

[package.metadata.vcpkg.target]
x86_64-unknown-linux-gnu = { dependencies = ["libvpx", "libyuv"] }
x86_64-pc-windows-msvc = { dependencies = ["libvpx:x64-windows-static", "libyuv:x64-windows-static"] }


