[package]
name = "l5p-kb-rgb"
version = "0.1.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parking_lot = "*"
fltk = "*"
rand = "*"

[dependencies.hidapi]
version = "*"
default-features = false
features=["linux-static-hidraw"]