# Depends on https://github.com/sagiegurari/cargo-make - Install it with "cargo install cargo-make"
# After that you can run "cargo make build" or "cargo make build-release" to build the project

# Building
[tasks.build]
windows_alias = "build-windows"
linux_alias = "build-linux"

[tasks.build-windows]
dependencies = ["setup-vcpkg"]
env = { VCPKG_INSTALLATION_ROOT = "${CARGO_MAKE_WORKING_DIRECTORY}\\target\\vcpkg" }
command = "cargo"
args = ["build"]

[tasks.build-linux]
dependencies = ["setup-vcpkg"]
env = { VCPKG_INSTALLATION_ROOT = "~/bin/vcpkg" }
command = "cargo"
args = ["build"]

[tasks.build-release]
windows_alias = "build-release-windows"
linux_alias = "build-release-linux"

[tasks.build-release-windows]
dependencies = ["setup-vcpkg"]
env = { VCPKG_INSTALLATION_ROOT = "${CARGO_MAKE_WORKING_DIRECTORY}\\target\\vcpkg" }
command = "cargo"
args = ["build", "--release"]

[tasks.build-release-linux]
dependencies = ["setup-vcpkg"]
env = { VCPKG_INSTALLATION_ROOT = "~/bin/vcpkg" }
command = "cargo"
args = ["build", "--release"]

[tasks.setup-vcpkg]
command = "cargo"
args = ["vcpkg", "build"]

# Clippy
[tasks.clippy-all]
windows_alias = "clippy-all-windows"
linux_alias = "clippy-all-linux"

[tasks.clippy-all-windows]
env = { VCPKG_INSTALLATION_ROOT = "${CARGO_MAKE_WORKING_DIRECTORY}\\target\\vcpkg" }
script = '''
cls && cargo clippy -- -W clippy::pedantic
'''

[tasks.clippy-all-linux]
env = { VCPKG_INSTALLATION_ROOT = "~/bin/vcpkg" }
script = '''
clear && cargo clippy -- -W clippy::pedantic
'''
