use device_query::Keycode;

const KEYS_ZONE_1: [Keycode; 24] = [
    Keycode::Escape,
    Keycode::F1,
    Keycode::F2,
    Keycode::F3,
    Keycode::F4,
    Keycode::Grave,
    Keycode::Key1,
    Keycode::Key2,
    Keycode::Key3,
    Keycode::Key4,
    Keycode::Tab,
    Keycode::Q,
    Keycode::W,
    Keycode::E,
    Keycode::CapsLock,
    Keycode::A,
    Keycode::S,
    Keycode::D,
    Keycode::LShift,
    Keycode::Z,
    Keycode::X,
    Keycode::LControl,
    Keycode::LMeta,
    Keycode::LAlt,
];

const KEYS_ZONE_2: [Keycode; 29] = [
    Keycode::F5,
    Keycode::F6,
    Keycode::F7,
    Keycode::F8,
    Keycode::F9,
    Keycode::F10,
    Keycode::Key5,
    Keycode::Key6,
    Keycode::Key7,
    Keycode::Key8,
    Keycode::Key9,
    Keycode::R,
    Keycode::T,
    Keycode::Y,
    Keycode::U,
    Keycode::I,
    Keycode::F,
    Keycode::G,
    Keycode::H,
    Keycode::J,
    Keycode::K,
    Keycode::C,
    Keycode::V,
    Keycode::B,
    Keycode::N,
    Keycode::M,
    Keycode::Comma,
    Keycode::Space,
    Keycode::RAlt,
];

const KEYS_ZONE_3: [Keycode; 25] = [
    Keycode::F11,
    Keycode::F12,
    Keycode::Insert,
    Keycode::Delete,
    Keycode::Key0,
    Keycode::Minus,
    Keycode::Equal,
    Keycode::Backspace,
    Keycode::O,
    Keycode::P,
    Keycode::LeftBracket,
    Keycode::RightBracket,
    Keycode::Enter,
    Keycode::L,
    Keycode::Semicolon,
    Keycode::Apostrophe,
    Keycode::BackSlash,
    Keycode::Dot,
    Keycode::Slash,
    Keycode::RShift,
    Keycode::RControl,
    Keycode::Up,
    Keycode::Down,
    Keycode::Left,
    Keycode::Right,
];

const KEYS_ZONE_4: [Keycode; 18] = [
    Keycode::Home,
    Keycode::End,
    Keycode::PageUp,
    Keycode::PageDown,
    Keycode::NumpadDivide,
    Keycode::NumpadMultiply,
    Keycode::NumpadSubtract,
    Keycode::Numpad7,
    Keycode::Numpad8,
    Keycode::Numpad9,
    Keycode::Numpad4,
    Keycode::Numpad5,
    Keycode::Numpad6,
    Keycode::NumpadAdd,
    Keycode::Numpad1,
    Keycode::Numpad2,
    Keycode::Numpad3,
    Keycode::Numpad0,
];

pub const KEY_ZONES: [&[Keycode]; 4] = [&KEYS_ZONE_1, &KEYS_ZONE_2, &KEYS_ZONE_3, &KEYS_ZONE_4];
