#[cfg(target_os = "windows")]
mod platform {
    use device_query::Keycode;

    pub const KEYS_ZONE_1: [Keycode; 24] = [
        Keycode::Escape,
        Keycode::F1,
        Keycode::F2,
        Keycode::F3,
        Keycode::F4,
        Keycode::Grave,
        Keycode::Key1,
        Keycode::Key2,
        Keycode::Key3,
        Keycode::Key4,
        Keycode::Tab,
        Keycode::Q,
        Keycode::W,
        Keycode::E,
        Keycode::CapsLock,
        Keycode::A,
        Keycode::S,
        Keycode::D,
        Keycode::LShift,
        Keycode::Z,
        Keycode::X,
        Keycode::LControl,
        Keycode::LMeta,
        Keycode::LAlt,
    ];

    pub const KEYS_ZONE_2: [Keycode; 29] = [
        Keycode::F5,
        Keycode::F6,
        Keycode::F7,
        Keycode::F8,
        Keycode::F9,
        Keycode::F10,
        Keycode::Key5,
        Keycode::Key6,
        Keycode::Key7,
        Keycode::Key8,
        Keycode::Key9,
        Keycode::R,
        Keycode::T,
        Keycode::Y,
        Keycode::U,
        Keycode::I,
        Keycode::F,
        Keycode::G,
        Keycode::H,
        Keycode::J,
        Keycode::K,
        Keycode::C,
        Keycode::V,
        Keycode::B,
        Keycode::N,
        Keycode::M,
        Keycode::Comma,
        Keycode::Space,
        Keycode::RAlt,
    ];

    pub const KEYS_ZONE_3: [Keycode; 25] = [
        Keycode::F11,
        Keycode::F12,
        Keycode::Insert,
        Keycode::Delete,
        Keycode::Key0,
        Keycode::Minus,
        Keycode::Equal,
        Keycode::Backspace,
        Keycode::O,
        Keycode::P,
        Keycode::LeftBracket,
        Keycode::RightBracket,
        Keycode::Enter,
        Keycode::L,
        Keycode::Semicolon,
        Keycode::Apostrophe,
        Keycode::BackSlash,
        Keycode::Dot,
        Keycode::Slash,
        Keycode::RShift,
        Keycode::RControl,
        Keycode::Up,
        Keycode::Down,
        Keycode::Left,
        Keycode::Right,
    ];

    pub const KEYS_ZONE_4: [Keycode; 18] = [
        Keycode::Home,
        Keycode::End,
        Keycode::PageUp,
        Keycode::PageDown,
        Keycode::NumpadDivide,
        Keycode::NumpadMultiply,
        Keycode::NumpadSubtract,
        Keycode::Numpad7,
        Keycode::Numpad8,
        Keycode::Numpad9,
        Keycode::Numpad4,
        Keycode::Numpad5,
        Keycode::Numpad6,
        Keycode::NumpadAdd,
        Keycode::Numpad1,
        Keycode::Numpad2,
        Keycode::Numpad3,
        Keycode::Numpad0,
    ];

    pub const KEY_ZONES: [&[Keycode]; 4] = [&KEYS_ZONE_1, &KEYS_ZONE_2, &KEYS_ZONE_3, &KEYS_ZONE_4];
}

#[cfg(target_os = "linux")]
mod platform {
    use evdev::Key;

    pub const KEYS_ZONE_1: [Key; 24] = [
        Key::KEY_ESC,
        Key::KEY_F1,
        Key::KEY_F2,
        Key::KEY_F3,
        Key::KEY_F4,
        Key::KEY_GRAVE,
        Key::KEY_1,
        Key::KEY_2,
        Key::KEY_3,
        Key::KEY_4,
        Key::KEY_TAB,
        Key::KEY_Q,
        Key::KEY_W,
        Key::KEY_E,
        Key::KEY_CAPSLOCK,
        Key::KEY_A,
        Key::KEY_S,
        Key::KEY_D,
        Key::KEY_LEFTSHIFT,
        Key::KEY_Z,
        Key::KEY_X,
        Key::KEY_LEFTCTRL,
        Key::KEY_LEFTMETA,
        Key::KEY_LEFTALT,
    ];

    pub const KEYS_ZONE_2: [Key; 29] = [
        Key::KEY_F5,
        Key::KEY_F6,
        Key::KEY_F7,
        Key::KEY_F8,
        Key::KEY_F9,
        Key::KEY_F10,
        Key::KEY_5,
        Key::KEY_6,
        Key::KEY_7,
        Key::KEY_8,
        Key::KEY_9,
        Key::KEY_R,
        Key::KEY_T,
        Key::KEY_Y,
        Key::KEY_U,
        Key::KEY_I,
        Key::KEY_F,
        Key::KEY_G,
        Key::KEY_H,
        Key::KEY_J,
        Key::KEY_K,
        Key::KEY_C,
        Key::KEY_V,
        Key::KEY_B,
        Key::KEY_N,
        Key::KEY_M,
        Key::KEY_COMMA,
        Key::KEY_SPACE,
        Key::KEY_RIGHTALT,
    ];

    pub const KEYS_ZONE_3: [Key; 25] = [
        Key::KEY_F11,
        Key::KEY_F12,
        Key::KEY_INSERT,
        Key::KEY_DELETE,
        Key::KEY_0,
        Key::KEY_MINUS,
        Key::KEY_EQUAL,
        Key::KEY_BACKSPACE,
        Key::KEY_O,
        Key::KEY_P,
        Key::KEY_LEFTBRACE,
        Key::KEY_RIGHTBRACE,
        Key::KEY_ENTER,
        Key::KEY_L,
        Key::KEY_SEMICOLON,
        Key::KEY_APOSTROPHE,
        Key::KEY_BACKSLASH,
        Key::KEY_DOT,
        Key::KEY_SLASH,
        Key::KEY_RIGHTSHIFT,
        Key::KEY_RIGHTCTRL,
        Key::KEY_UP,
        Key::KEY_DOWN,
        Key::KEY_LEFT,
        Key::KEY_RIGHT,
    ];

    pub const KEYS_ZONE_4: [Key; 18] = [
        Key::KEY_HOME,
        Key::KEY_END,
        Key::KEY_PAGEUP,
        Key::KEY_PAGEDOWN,
        Key::KEY_KPSLASH,
        Key::KEY_KPASTERISK,
        Key::KEY_KPMINUS,
        Key::KEY_KP7,
        Key::KEY_KP8,
        Key::KEY_KP9,
        Key::KEY_KP4,
        Key::KEY_KP5,
        Key::KEY_KP6,
        Key::KEY_KPPLUS,
        Key::KEY_KP1,
        Key::KEY_KP2,
        Key::KEY_KP3,
        Key::KEY_KP0,
    ];

    pub const KEY_ZONES: [&[Key]; 4] = [&KEYS_ZONE_1, &KEYS_ZONE_2, &KEYS_ZONE_3, &KEYS_ZONE_4];
}

pub use platform::*;
