[package]
name = "legion-rgb-driver"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.38"
hidapi = { version = "2.1.2", default-features = false, features = [
    "linux-static-libusb",
] }
