name: Compile changes

on:
  push:
    branches-ignore:
     'main'
  pull_request:
    branches-ignore:
      'main'

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Compile for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: linux
            os: ubuntu-latest
            artifact_name: target/release/l5p-kb-rgb
            asset_name: l5p-kb-rgb-linux
          - name: windows
            os: windows-latest
            artifact_name: target/release/l5p-kb-rgb.exe
            asset_name: l5p-kb-rgb-windows
          - name: macos
            os: macos-latest
            artifact_name: target/release/l5p-kb-rgb
            asset_name: l5p-kb-rgb-macos

    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: '10.0'
      - name: Download dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
           sudo apt-get update && sudo apt-get install -y libpango1.0-dev libx11-dev libxext-dev libxft-dev libxinerama-dev libxcursor-dev libxrender-dev libxfixes-dev libudev-dev nasm libxcb-randr0-dev
           vcpkg update && vcpkg install libvpx libyuv
          elif [ "$RUNNER_OS" == "macOS" ]; then
           brew install nasm
           vcpkg update && vcpkg install libvpx libyuv
          elif [ "$RUNNER_OS" == "Windows" ]; then
           vcpkg update && vcpkg install libvpx:x64-windows-static libyuv:x64-windows-static
          fi
        shell: bash
      - uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: cargo build --release --verbose
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.asset_name }}
        path: ${{ matrix.artifact_name }}
